/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dsa_rps_cortez.java;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Player 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel2.setText("Player 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        jLabel3.setText("[3] = Paper");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel4.setText("[1] = Rock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel5.setText("[2] = Scissor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        VS.setText("vs");
        VS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSActionPerformed(evt);
            }
        });
        getContentPane().add(VS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 173, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSActionPerformed
         
        int p1 = Integer.parseInt(txt1.getText());
        int p2 = Integer.parseInt(txt2.getText());
        
        if(p1 == 1 && p2 == 1)
        {
        JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", HEIGHT);
        }
        else if(p1 == 1 && p2 == 2)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 1 && p2 == 3)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 2 && p2 == 1)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 2 && p2 == 2)
        {
        JOptionPane.showMessageDialog(rootPane, "DRAW!", "RPS", HEIGHT);
        }
        else if(p1 == 2 && p2 == 3)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 3 && p2 == 1)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 3 && p2 == 2)
        {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WINS!", "RPS", HEIGHT);
        }
        else if(p1 == 3 && p2 == 3)
        {
        JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", HEIGHT);
        }// TODO add yo ur handling code here:
    }//GEN-LAST:event_VSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}